<!-- Prendere un paragrafo abbastanza lungo, contenente diverse frasi.
Prendere il paragrafo e suddividerlo in tanti paragrafi <p>. Ogni punto un
nuovo paragrafo. -->

<?php

$dot = '.';
$paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec augue quam. Praesent a leo non justo bibendum tempus eget non orci. Nullam laoreet vel felis sed commodo. Integer nec aliquet urna. In lacinia et enim a hendrerit. Curabitur volutpat turpis sed sem vehicula, ut iaculis elit ornare. Integer sodales dui ac molestie malesuada. Integer ut nunc est. Etiam eu tincidunt lacus. Praesent a sem viverra massa euismod interdum. Vestibulum metus turpis, iaculis condimentum est eget, imperdiet vehicula neque. Vivamus sagittis ante eget tincidunt consequat. Donec a risus eget ipsum efficitur lobortis in quis metus. Nunc mollis nulla eget vestibulum venenatis. Ut sapien ligula, semper nec lobortis non, ornare non erat. Nullam auctor, nibh non scelerisque malesuada, sem neque consequat diam, at placerat tellus ipsum id purus. Curabitur id enim efficitur, convallis velit et, gravida lorem. Praesent accumsan nunc eu egestas mattis. Nullam congue a erat nec tincidunt. In a laoreet turpis. Curabitur sollicitudin tristique posuere. Fusce blandit purus at tellus consequat consequat. Donec mattis auctor diam in porta. Cras vestibulum finibus fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis risus in faucibus consequat. Nulla porta ornare purus sed aliquam. Aliquam aliquam diam ut ex fringilla malesuada. Nunc ut massa commodo, efficitur leo sit amet, cursus mauris. Nunc vehicula facilisis vulputate. Suspendisse odio diam, accumsan sed dictum non, blandit sed orci. Morbi in velit posuere, lobortis eros vitae, auctor tortor. Sed vitae tortor tincidunt, lobortis dolor tristique, malesuada mi. Proin malesuada tincidunt ante lobortis consequat. Nullam facilisis faucibus sodales. Vestibulum suscipit, quam ut eleifend pulvinar, turpis lacus gravida magna, sed placerat leo velit eu erat. Phasellus vehicula velit eget erat tempor interdum. Duis congue, erat nec vehicula vulputate, lacus nulla tempor diam, vitae cursus arcu magna non metus. Duis viverra turpis ac arcu pulvinar, eget viverra diam tristique. Curabitur ac lectus ut felis condimentum rhoncus. Aenean nec molestie magna. Maecenas dictum augue sit amet pharetra lacinia. Nulla facilisi. Cras ac tellus ut lacus consectetur interdum. Ut tristique justo vel arcu mollis euismod. Vestibulum dignissim a nulla vitae rhoncus. Etiam dapibus arcu non eros semper varius. Maecenas in blandit erat. Aliquam interdum sagittis mauris, ac cursus massa ullamcorper a. Cras tincidunt tempor lacus a finibus. Nunc sagittis pharetra risus sit amet pellentesque. Proin ultrices interdum facilisis. Nunc sagittis enim at lectus tempor molestie. Suspendisse feugiat, lacus ut tempor tincidunt, erat nisl ultrices odio, ut finibus nisl neque at dolor. Maecenas interdum elementum arcu sit amet dapibus. Vestibulum sed sagittis ligula. Phasellus quis eleifend nulla, ac eleifend ligula. Aliquam erat volutpat. ";
$stringArray = explode($dot,$paragraph);

for($i=0;$i<count($stringArray);$i++){
    echo '<p>'. $stringArray[$i] . "</p>";
}
?>